## Бинаризация - преобразования значение в 0 и 1

In [1]:
import numpy as np
from sklearn import preprocessing  # модуль для нормализации данных в sklearn

input_data = np.array([[5.1, -2.9, 3.3],
                      [-1.2, 7.8, -6.1],
                      [3.9, 0.4, 2.1]])

In [3]:
binarized_data = preprocessing.Binarizer(threshold=2.1).transform(input_data)
# разделитель = 2.1 - все значения выше 2.1 трактуются как True (1)
print(binarized_data) 

[[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


## Исключение среднего - каждый признак (feature) центрируется в 0

In [11]:
np.array([18, 2, 3]).mean() == (18+2+3)/3
# находит среднее арифметическое значение плоского (одномерного) массива

True

In [17]:
# Если массив не сплющен (flattened array), то надо указать ось, вдоль которой надо вычислить 
# среднее значение. axis=0 - среднее в колонках, axis=1 - среднее в строках
np.array([[18, 2, 3],
          [1, 2, 3]]).mean(axis=0) == [(18+1)/2, (2+2)/2, (3+3)/2]

array([ True,  True,  True])

In [23]:
means_along_columns = input_data.mean(axis=0)
scaled_data_along_columns = means_along_columns.std(axis=0)
print(means_along_columns, scaled_data_along_columns)

[ 2.6         1.76666667 -0.23333333] 1.1889408088351496


## Масштарование - принимаем средние значения за 0

## Когда может потребоваться обработка данных?

Допустим, у нас изображение $28\cdot 28$ пикселей, т.е. всего 256 пикселей.

# Tensor vs Array vs DataFrame