In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [6]:
# база данных ирисов с классификацией
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# имена для колнок
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']

# читаем и записываем в dataframe pandas
dataset = pd.read_csv(url, names=names)
dataset

sepal-length  sepal-width  petal-length  petal-width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [10]:
x = dataset.iloc[:, :-1].values # массив значений четырех колонок
y = dataset.iloc[:, 4].values # массив значений пятой колонки (тип ириса)

In [8]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [11]:
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [26]:
import numpy as np
x1 = np.arange(10)
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
x1.reshape((5, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [30]:
y = range(5) # здесь уже решейпнуть не получится
# к тому же, пока что это только генератор, а не готовый массив
y, list(y)

(range(0, 5), [0, 1, 2, 3, 4])

Теперь два эти массива поделим на тренировочные и тестовые данные (

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
x_train

array([[7.2, 3.6, 6.1, 2.5],
       [6.3, 2.9, 5.6, 1.8],
       [6.3, 2.5, 5. , 1.9],
       [7.7, 2.8, 6.7, 2. ],
       [6.5, 3. , 5.5, 1.8],
       [6.7, 3. , 5.2, 2.3],
       [6.2, 2.2, 4.5, 1.5],
       [5.5, 2.4, 3.8, 1.1],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.6, 2.9, 4.6, 1.3],
       [6. , 2.2, 5. , 1.5],
       [5.6, 2.9, 3.6, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [7.3, 2.9, 6.3, 1.8],
       [6.2, 2.9, 4.3, 1.3],
       [5.8, 2.6, 4. , 1.2],
       [5.4, 3.4, 1.7, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [6.5, 3. , 5.2, 2. ],
       [7.2, 3.2, 6. , 1.8],
       [5.9, 3. , 5.1, 1.8],
       [7.1, 3. , 5.9, 2.1],
       [5.6, 3. , 4.1, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [6.2, 2.8, 4.8, 1.8],
       [5. , 3.4, 1.6, 0.4],
       [5.5, 2.3, 4. , 1.3],
       [5.5, 3.5, 1.3, 0.2],
       [6.4, 2.8, 5.6, 2.1],
       [6.1, 3. , 4.6, 1.4],
       [5.5, 2.6, 4.4, 1.2],
       [5.1, 2.5, 3. , 1.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.4, 3