Вектор - матрица из одной строки или одного столбца

In [1]:
import numpy as np
vector = np.array([1, 2])
vector

array([1, 2])

Атрибут __str__ объекта [1, 2] и сам объект

In [6]:
zero_5D_vector = np.zeros((5))
print(zero_5D_vector)

[0. 0. 0. 0. 0.]


In [7]:
zero_5D_vector

array([0., 0., 0., 0., 0.])

Если 

In [12]:
zero_5D_vector_in_matrix = np.zeros((2, 5))
print(zero_5D_vector_in_matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


 (например, для возможности транспонирования матрицы - строки со столбцами меняются местами) $A_{m×n} = A^{T}_{n×m}$ или $A_{ij} = A^{T}_{ji}$

Пример:
$${\begin{bmatrix}1&2\\3&4\end{bmatrix}}^{{{\mathrm  {T}}}}\!\!\;\!=\,{\begin{bmatrix}1&3\\2&4\end{bmatrix}}, \quad {\begin{bmatrix}1&2\\3&4\\5&6\end{bmatrix}}^{{{\mathrm  {T}}}}\!\!\;\!=\,{\begin{bmatrix}1&3&5\\2&4&6\end{bmatrix}}\;$$

In [8]:
a = [[4, 5, 6], [-1, 2, 0], [2, 3, 5]]
b = [[2, 7, -3], [-2, -10, -11], [0, 1, 0]]
a+b # матрица с тремя столбцами и 6 строками, а не сумма (просто расширили список)

[[4, 5, 6], [-1, 2, 0], [2, 3, 5], [2, 7, -3], [-2, -10, -11], [0, 1, 0]]

In [3]:
a1 = np.array(a)
a1

array([[ 4,  5,  6],
       [-1,  2,  0],
       [ 2,  3,  5]])

In [9]:
b1 = np.array(b)
sum_ab = a1+b1 # поэлементное сложение
sum_ab

array([[  6,  12,   3],
       [ -3,  -8, -11],
       [  2,   4,   5]])

In [11]:
product_ab = a1*b1
product_ab

array([[  8,  35, -18],
       [  2, -20,   0],
       [  0,   3,   0]])